[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
payguard_escrow = "PaYGuaRDc2xSiLrq7WQ9EBkCqV2XvZQp9vYywYf8d3k"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"

